### ISSUE TITLE
Hacer Despliegue

### ISSUE THREAD

**Issue by jarrisondev** [GabrielCrackPro/fake-identity-generator#2]
No sé si se hace automáticamente o si lo debes hace tú, aún me sale la versión antigua.

**Comment by GabrielCrackPro** [comment]
Ya lo he desplegado yo 
Gracias por cierto 😁

**Comment by jarrisondev** [comment]
El enlace sigue mostrando la antigua versión.

**Comment by GabrielCrackPro** [comment]
> El enlace sigue mostrando la antigua versión.

En principio no debería. Lo volví a desplegar pero lo miraré cuando tenga tiempo

**Comment by GabrielCrackPro** [comment]
Vale ya se ve bien
No se porque el enlace no se actualizaba
Me ha tocado hacer el despliegue en otro diferentre Que raro
fakeid-generator.surge.sh
